// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_praise_name_ from "./routes/api/praise/[name].ts";
import * as $delete from "./routes/delete.tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $DeleteBox from "./islands/DeleteBox.tsx";
import * as $PraiseBox from "./islands/PraiseBox.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/praise/[name].ts": $api_praise_name_,
    "./routes/delete.tsx": $delete,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/DeleteBox.tsx": $DeleteBox,
    "./islands/PraiseBox.tsx": $PraiseBox,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
